controller_joint_names: ['FrontRightWheelJoint','FrontLeftWheelJoint','right_frontaxisjoint','left_frontaxisjoint']
toycar:

  joint_state_controller:
    type        : "joint_state_controller/JointStateController"
    publish_rate: 150.0               # default: 50
  # Velocity Controllers ---------------------------------------
  joint1_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FrontRightWheelJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}


  joint2_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: FrontLeftWheelJoint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  # joint3_velocity_controller:   
  #   type: velocity_controllers/JointVelocityController
  #   joint: rearwheelsjoints
  #   pid: {p: 100.0, i: 2.0, d: 1.0}


  #Position Controllers ---------------------------------------
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_frontaxisjoint
    pid: {p: 100.0, i: 2.0, d: 1.0}
  
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_frontaxisjoint
    pid: {p: 100.0, i: 2.0, d: 1.0}

  # joint6_position_controller:   
  #   type: effort_controllers/JointPositionController
  #   joint: rearwheelsjoints
  #   pid: {p: 100.0, i: 2.0, d: 1.0}